# name: Auto update at the end of each day
# on:
#   schedule:
#     - cron: "0 0 * * *" # At the end of each day

name: Auto update at the end of each day
on: [push]

jobs:
  updater:
    name: Daily auto update
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm i
        env:
          CI: true
      - name: Run
        run: npm run dev
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
